10 REM COMPRA DE DIVISAS
20 INPUT "A CUANTO ESTA EL DOLAR"; D
30 INPUT "A CUANTO ESTA EL YEN"; Y
40 INPUT "CUANTAS PESETAS QUIERES CAMBIAR"; X
50 PRINT "QUIERES COMPRAR DOLARES (1) O YENES (2)"
60 INPUT "(CONTESTA 1 O 2)"; A
70 IF A = 2 THEN GOTO 110
80 N = X / D
90 PRINT X; "PESETAS SON AL CAMBIO"; N; "DOLARES"
100 GOTO 130
110 N = X / Y
120 PRINT X; "PESETAS SON AL CAMBIO"; N; "YENES"
130 END

