10 REM LANZAMIENTO DE UN DADO Y REFLEJOS
15 CLS
16 LET N = 1
21 PRINT ; N; N; N; N; N; N; N; N; N; N; N; N; N; N; N; N; N; N; N; N; N; N; N; N; N; N
22 LET R = R + 1: REM SE REGISTRA EL PRIMER PASE
25 LET N = N + 1
26 IF N > 6 THEN LET N = 1
30 LET A$ = INKEY$
40 IF A$ = "" THEN GOTO 21: REM MIENTRAS NO SE PULSE UNA TECLA EL PROGRAMA VUELVE A LA LINEA 21
41 IF N > 1 THEN GOTO 43: REM CUANDO EL ULTIMO VALOR DE N ES MAYOR Q 1 EL ULTIMO NUMERO IMPRESO VALE N-1
42 IF N = 1 THEN LET N = 6: GOTO 45
43 IF N > 1 THEN LET N = N - 1
45 PRINT "N="; N
46 PRINT "R="; R
50 END
REM "PARA CAMBIAR EL NUMERO DE CARAS DEL DADO (C):"
REM "SUSTITUIR LOS 6 DE LAS LINEAS 26 Y 42 POR EL NUEVO VALOR DE C"



