10 REM MEDIA DE UNA SERIE
20 PRINT "CADA VEZ QUE APAREZCA UNA INTERROGACION EN LA PANTALLA INTRODUCE UN NUMERO DE LA SERIE Y PULSA ENTER. CUANDO HAYAS INTRODUCIDO TODOS LOS DATOS,": PRINT "INTRODUCE EL DATO `0`, O SIMPLEMENTE PULSA `ENTER`"
23 GOTO 30
25 PRINT
30 INPUT ; D
40 IF D = 0 THEN GOTO 80
50 N = N + 1
60 S = S + D
70 GOTO 25
80 M = S / N
85 PRINT
90 PRINT "LA MEDIA ES: "; M
95 PRINT "EL NUMERO DE DATOS ES: "; N
100 LET A$ = INKEY$
110 IF A$ = "" THEN GOTO 100
120 CLS
130 END

